#!/usr/bin/env ruby

require "open3"

RED = "\e[31m"
GREEN = "\e[32m"
CYAN = "\e[36m"
RESET = "\e[m"

class BenchCommand
	def shell(s)
		output, error, process = Open3.capture3(s)
		if error.size > 0
			@sh_error = ""
			error.split("\n").each do |s|
				next if s.include? "JAVA_OPTIONS"
				@sh_error += RED + s + RESET + "\n"
			end
		end
		output
	end

	def show_help()
		puts
		puts "usage: bench <mode> <target> <lang>"
		puts
		puts "<mode> = " + @modes.join(" | ")
		puts 
		puts "<target> = all | " + @targets.join(" | ")
		puts
		puts "<lang> = all | " + @langs.join(" | ")
		puts
	end

	def print_shell_error()
		if @sh_error.size > 0
			STDERR.puts RED + "[ERROR]" + RESET
			puts @sh_error
		end
	end

	def source_path(target)
		"src/#{target}"
	end

	def build_path(target,lang)
		"build/#{target}-#{lang}"
	end

	def apply_wildcard(str,target,lang)
		wildcards = {
			"%" => target.to_s,
			"<src>" => source_path(target),
			"<bld>" => build_path(target,lang)
		}

		result = str

		wildcards.keys.each do |key|
			result.gsub!(key, wildcards[key])
		end

		result
	end

	def run_with(target,lang)
		if @build_tasks.keys.include? lang
			if !Dir.exists?(build_path(target,lang))
				build_with(target,lang)
			end
		end

		command = apply_wildcard(@commands[lang],target,lang).split("|")
		result = shell(command[0])
		puts @langnames[lang] + "\t" + result

		# print error
		print_shell_error()

		# remove chache etc...
		if command.size > 1
			shell(command[1])
		end
	end

	def build_with(target,lang)
		command = apply_wildcard(@build_tasks[lang],target,lang)

		STDERR.puts GREEN + "[BUILD] #{target} / #{lang} ..." + RESET
		shell("rm -rf "+build_path(target,lang))
		shell("mkdir -p "+build_path(target,lang))
		shell(command)+build_path(target,lang)
		print_shell_error()
	end

	def clean_with(target,lang)
		STDERR.puts CYAN + "[CLEAN] #{target} / #{lang} ..." + RESET
		shell("rm -rf "+build_path(target,lang))
	end

	def do_task(target, lang, target_all, lang_all, process_method_name)
		lang_list = nil
		target_list = nil

		if target == :all
			target_list = target_all
		elsif target_all.include? target
			target_list = [target]
		else
			return
		end

		if lang == :all
			lang_list = lang_all
		elsif lang_all.include? lang
			lang_list = [lang]
		else
			return
		end

		process_method = self.method(process_method_name)

		target_list.each{|target|
			lang_list.each{|lang|
				process_method.call(target,lang)
			}
		}

		# print_shell_error()
	end

	def run(target,lang)
		do_task(target,lang,@targets,@langs,"run_with")
	end

	def build(target,lang)
		do_task(target,lang,@targets,@build_tasks.keys,"build_with")
	end

	def clean(target,lang)
		do_task(target,lang,@targets,@build_tasks.keys,"clean_with")
	end

	def main()
		if !@modes.include? @mode
			show_help()
			return
		end

		if @mode == :help
			show_help()
			return
		end

		if @mode == :build
			build(@arg1,@arg2)
			return
		end

		if @mode == :clean
			clean(@arg1,@arg2)
			return
		end

		if @mode == :run
			run(@arg1,@arg2)
			return
		end
	end

	def rbenv(version)
		"~/.rbenv/versions/" + @ruby_versions[version] + "/bin/ruby"
	end

	def pyenv(version)
		"~/.pyenv/versions/" + @python_versions[version] + "/bin/python"
	end

	def pythonpath()
		"export PYTHONPATH=`pwd`:$PYTHONPATH;"
	end

	def rubylib()
		"export RUBYLIB=`pwd`:$RUBYLIB;"
	end

	def python_rm()
		"rm -rf lib/__pycache__ rm lib/*.pyc"
	end

	def jvm(version,command)
		"`/usr/libexec/java_home -v '" + @java_versions[version] + "'`/bin/" + command
	end

	def java(version)
		jvm(version,"java")
	end

	def javac(version)
		jvm(version,"javac")
	end

	def gvm(command)
		"export GROOVY_HOME=~/.gvm/#{@groovy_version}/current; ~/.gvm/groovy/"+@groovy_version+"/bin/"+command
	end

	def scalaenv(command)
		"~/.scalaenv/versions/scala-"+@scala_version+"/bin/"+command
	end

	def gopath()
		"export GOPATH=`pwd`/lib/golib:$GOPATH;"
	end

	def initialize()
		@opts = ARGV.select{|s| s.start_with? '-'}.map{|s| s.split('-').join}
		@args = ARGV.select{|s| !(s.start_with? '-')}

		@sh_error = ""
		@mode = @opts[0].to_s.to_sym
		@arg1 = @args[0].to_s.to_sym
		@arg2 = @args[1].to_s.to_sym

		@ruby_versions = {
			:ruby => "2.1.2",
			:rubinius => "rbx-2.2.9",
			:jruby => "jruby-1.7.9"
		}

		@python_versions = {
			:python => "3.4.0",
			:pypy => "pypy-2.3.1",
			:jython => "jython-2.7-beta2"
		}

		@java_versions = {
			:java6 => "1.6*",
			:java7 => "1.7*"
		}

		@groovy_version = "2.3.4"
		@scala_version = "2.11.0"
		@go_compiler = "6g"
		@go_linker = "6l"

		@commands = {
			:c => "<bld>/%.out",
			:cpp => "<bld>/%.out",
			:ruby => "#{rubylib} #{rbenv(:ruby)} <src>/%.rb",
			:rubinius => "#{rubylib} #{rbenv(:rubinius)} <src>/%.rb",
			:jruby => "#{rubylib} #{rbenv(:jruby)} <src>/%.rb",
			:python => "#{pythonpath} #{pyenv(:python)} <src>/%.py | #{python_rm}",
			:pypy => "#{pythonpath} #{pyenv(:pypy)} <src>/%.py | #{python_rm}",
			:jython => "#{pythonpath} #{pyenv(:jython)} <src>/%.py | #{python_rm}",
			:java => "#{java(:java7)} -cp <bld> %",
			:groovy => "#{gvm("groovy")} -cp lib <src>/%.groovy",
			:groovys => "#{gvm("groovy")} -cp lib <src>/%_s.groovy",
			:scala => "#{scalaenv("scala")} -cp <bld> %",
			:go => "#{gopath} go run <src>/%.go",
			:d => "<bld>/%.out",
		}

		@langnames = {
			:c => "C (gcc -O3)",
			:cpp => "C++ (g++ -O3)",
			:ruby => "Ruby",
			:rubinius => "Rubinius",
			:jruby => "JRuby",
			:python => "Python",
			:pypy => "PyPy",
			:jython => "Jython",
			:java => "Java",
			:groovy => "Groovy(Dynamic)",
			:groovys => "Groovy(Static)",
			:scala => "Scala",
			:go => "Go",
			:d => "D (dmd -O)",
		}

		@build_tasks = {
			:c => "gcc -w -O3 -Ilib <src>/%.c -o <bld>/%.out",
			:cpp => "g++ -w -Wall -O3 -Ilib <src>/%.cpp -o <bld>/%.out",
			:java => "#{javac(:java7)} -cp <src>:lib <src>/%.java -d <bld>",
			:scala => "#{scalaenv("scalac")} lib/scalalib/*.scala -d <bld>; #{scalaenv("scalac")} -cp <bld> <src>/%.scala -d <bld>",
			:d => "dmd -O lib/Bench.d <src>/%.d -of<bld>/%.out",
		}

		@modes = [:run,:build,:clean,:help]
		@targets = [:tarai]
		@langs = @commands.keys

		main()
	end
end

bench = BenchCommand.new


